version: '3'
services:
  ssp-infra-postgres:
    image: postgres:latest
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - 5432:5432
    networks:
      - microservices
    volumes:
      - postgresql-data:/var/lib/postgresql/data/pgdata
      - /opt/log:/var/lib/postgresql/data/pg_log
  todo-task-service:
    image: registry.dev.policiacivil.sp.gov.br:5000/todo-online-api-service:0.0.1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms192m -Xmx192m
      - DATASOURCE_URL=jdbc:postgresql://ssp-infra-postgres:5432/todo
      - DATASOURCE_USERNAME=postgres
      - "DATASOURCE_PASSWORD=postgres"
    ports:
      - 3088:3088
    networks:
      - microservices
    volumes:
      - /opt/log:/opt/log

volumes:
  postgresql-data:
    driver: local
  logs:
    driver: local

networks:
  microservices:
    driver: overlay
