version: '3.5'
services:
  ##
  # Documentação
  # - https://github.com/jboss-dockerfiles/keycloak/tree/master/server
  # - https://www.keycloak.org/documentation.html
  ##
  keycloak:
    image: viana.cloud.prodesp.sp.gov.br/ipea/infra-keycloak:latest
    environment:
      # Levels suportados = ALL, DEBUG, ERROR, FATAL, INFO, OFF, TRACE and WARN
      - ROOT_LOGLEVEL=INFO
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_USER=keycloak
      - "KEYCLOAK_PASSWORD=keycloak@123"
      # Valores suportados:dipol-dev e dipol-prod 
      - "KEYCLOAK_IMPORT=dipol-prod"
      - DB_VENDOR=postgres
      - DB_ADDR=postgresql
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - "DB_PASSWORD=postgres@123"
      - JDBC_PARAMS='connectTimeout=30'
      - PORT=8081
      #- URL_APP_DOWNLOAD=[valor]
      - URL_RECOGNITION=https://sandbox.saffe.co/v0
      - KEY_API_RECOGNITION=saffe.dipol@sp.gov.br
      - "SECRET_API_RECOGNITION=qMNAOOkjTtA82Jfkf5wVicy7"
      - URL_IMAB=http://ws.e-cnhsp.sp.gov.br:80/eaigefor/ECNHService
      - "USER_IMAB=07163639000137"
      - "PASSWORD_IMAB=R357@R7"
      #- TIMEOUT=[valor]
      #- SOCKET_TIMEOUT=[valor]
      - DB2_ADDR=10.200.35.62
      - DB2_PORT=50000
      - DB2_DATABASE=RDO_PRD
      - DB2_USER=alterar_usuario
      - DB2_PASSWORD=alterar_senha
    ports:
      - 8081:8081
    networks:
      - microservices
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512m
      placement:
        constraints: [node.role == manager]

networks:
  microservices:
    driver: overlay
