version: '3'
services:
  todo-task-service:
    image: danilojava/todo-online-api-service:0.0.1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms192m -Xmx192m
      - DATASOURCE_URL=jdbc:postgresql://postgresql-teste:5432/todo
      - DATASOURCE_USERNAME=postgres
      - "DATASOURCE_PASSWORD=postgres"
    ports:
      - 3088:3088
    networks:
      - microservices
    volumes:
      - /opt/log:/opt/log
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512m
      placement:
        constraints: [node.role == manager]

volumes:
  postgresql-data:
    driver: local
  logs:
    driver: local

networks:
  microservices:
    driver: overlay
